# Database Server Configuration

# Base Image path
# Using the very minimal image of Python alpine to keep the image tiny as it just required to install postgres
FROM python:3.8

# TODO: Move these ENV to env file
#ENV E_DB_VOL_POINT=/home/rishi/productVentures/product/translator/dockervolume/postgres

# Move following env var to env file for compose
#ENV DATABASE=postgres
#ENV DB_HOST=localhost
ENV DB_PORT=5432

ENV DB_NAME=translator
ENV DB_USERNAME=db_translator
ENV DB_PASSWORD=intel

# Install Dependencies
RUN apt-get update \
    && apt-get --no-install-recommends install -y \
        ca-certificates \
        apt-transport-https \
        lsb-release \
    # Cleanup after installation
   && apt-get clean -y \
   && apt-get autoclean -y \
   && apt-get autoremove -y \
   && rm -rf /var/lib/apt/lists/*

# Add the PostgreSQL PGP key to verify their Debian packages.
# It should be the same key as https://www.postgresql.org/media/keys/ACCC4CF8.asc
RUN apt-key adv --keyserver hkp://p80.pool.sks-keyservers.net:80 --recv-keys B97B0AFCAA1A47F044F244A07FCC7D46ACCC4CF8

# Add PostgreSQL's repository. It contains the most recent stable release of PostgreSQL, ``11``.
RUN echo "deb http://apt.postgresql.org/pub/repos/apt/ $(lsb_release -cs)-pgdg main" > /etc/apt/sources.list.d/pgdg.list

#  There are some warnings (in red) that show up during the build. You can hide
#  them by prefixing each apt-get statement with DEBIAN_FRONTEND=noninteractive
RUN apt-get update \
    && apt-get --no-install-recommends install -y \
        postgresql-11 \
        postgresql-client-11 \
        postgresql-contrib-11 \
        libpq-dev

USER postgres

# Create a PostgreSQL role/user with the password and then create a database owned by the that user.
# TODO: Get the user/db name from env
RUN /etc/init.d/postgresql start \
    && psql --command "CREATE USER ${DB_USERNAME} WITH PASSWORD '${DB_PASSWORD}';" \
    && psql --command "CREATE DATABASE ${DB_NAME};" \
    && psql --command "ALTER ROLE db_translator SET client_encoding TO 'utf8';" \
    && psql --command "ALTER ROLE db_translator SET client_encoding TO 'utf8';" \
    && psql --command "GRANT ALL PRIVILEGES ON DATABASE translator TO db_translator;"
    #createdb -O db_translator translator

# Adjust PostgreSQL configuration so that remote connections to the database are possible.
RUN echo "host all  all    0.0.0.0/0  md5" >> /etc/postgresql/11/main/pg_hba.conf

# And add ``listen_addresses`` to ``/etc/postgresql/11/main/postgresql.conf``
RUN echo "listen_addresses='*'" >> /etc/postgresql/11/main/postgresql.conf

# Expose the PostgreSQL port
EXPOSE $DB_PORT

# Add VOLUMEs to allow backup of config, logs and databases
# The docker run command initializes these volume with any data that exists at the specified location within the base image.
# This Dockerfile results in an image that causes docker run to create a new mount point at sepecified locations
# and copy files into the newly created volume.
# These volumes will be created at run time by docker on host system
#TODO: Work on volumes
VOLUME  ["/var/log/postgresql", "/var/lib/postgresql/11/main"]

# Set the default command to run when starting the container
# Start the Postgresql database
CMD ["/usr/lib/postgresql/11/bin/postgres", "-D", "/var/lib/postgresql/11/main", "-c", "config_file=/etc/postgresql/11/main/postgresql.conf"]

