# Base file for development
FROM python:3.8

# set environment variables
# PYTHONDONTWRITEBYTECODE: Prevents Python from writing pyc files to disc (equivalent to python -B option)
# PYTHONUNBUFFERED: Prevents Python from buffering stdout and stderr (equivalent to python -u option)
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

# Install Dependencies
RUN apt-get update \
    && apt-get --no-install-recommends install -y \
        curl \
        ca-certificates \
        apt-transport-https \
        lsb-release \
        # python3-pip \
        build-essential \
        libssl-dev \
        libffi-dev \
        python3-dev \
        # Install Supervisor
        # supervisor 
    # Cleanup after installation
   && apt-get clean -y \
   && apt-get autoclean -y \
   && apt-get autoremove -y \
   && rm -rf /var/lib/apt/lists/*

# Installing supervisor as a seperate RUN command so that it can install recommended packages as well which are disallowed in above RUN command
RUN apt-get update && apt-get install -y supervisor

# Install PIP packages
RUN pip3 install --upgrade pip setuptools wheel

# Set Work Dir, If the WORKDIR doesn’t exist, it will be created automatically
WORKDIR /usr/src/translator/

#COPY ./dockerfiles/supervisord.conf /etc/supervisor

#CMD ["/usr/bin/supervisord", "-c", "/etc/supervisor/supervisord.conf"]
