# Generated by Django 2.2.7 on 2019-11-28 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TranslateDetails',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('src_language', models.CharField(max_length=200)),
                ('tgt_language', models.CharField(max_length=200)),
                ('total_bytes', models.IntegerField(blank=True, null=True)),
                ('mode', models.CharField(blank=True, max_length=2, null=True)),
                ('amount', models.FloatField(blank=True, null=True)),
                ('process_time', models.FloatField(blank=True, null=True)),
                ('translated_on', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'translate_details',
            },
        ),
    ]
