# Database Server Configuration

FROM python:3.8

ARG APP_DB_NAME
ARG APP_DB_USERNAME
ARG APP_DB_PASSWORD

# Install Dependencies
RUN apt-get update \
    && apt-get --no-install-recommends install -y \
        ca-certificates \
        apt-transport-https \
        lsb-release \
    # Cleanup after installation
   && apt-get clean -y \
   && apt-get autoclean -y \
   && apt-get autoremove -y \
   && rm -rf /var/lib/apt/lists/*

RUN apt-key adv --keyserver hkp://p80.pool.sks-keyservers.net:80 --recv-keys B97B0AFCAA1A47F044F244A07FCC7D46ACCC4CF8

RUN echo "deb http://apt.postgresql.org/pub/repos/apt/ $(lsb_release -cs)-pgdg main" > /etc/apt/sources.list.d/pgdg.list

RUN apt-get update \
    && apt-get --no-install-recommends install -y \
        postgresql-11 \
        postgresql-client-11 \
        postgresql-contrib-11 \
        libpq-dev

USER postgres

RUN /etc/init.d/postgresql start \
    && psql --command "CREATE USER ${APP_DB_USERNAME} WITH PASSWORD '${APP_DB_PASSWORD}';" \
    && psql --command "CREATE DATABASE ${APP_DB_NAME};" \
    && psql --command "ALTER ROLE ${APP_DB_USERNAME} SET client_encoding TO 'utf8';" \
    && psql --command "ALTER ROLE ${APP_DB_USERNAME} SET client_encoding TO 'utf8';" \
    && psql --command "GRANT ALL PRIVILEGES ON DATABASE ${APP_DB_NAME} TO ${APP_DB_USERNAME};"

RUN echo "host all  all    0.0.0.0/0  md5" >> /etc/postgresql/11/main/pg_hba.conf

RUN echo "listen_addresses='*'" >> /etc/postgresql/11/main/postgresql.conf

CMD ["/usr/lib/postgresql/11/bin/postgres", "-D", "/var/lib/postgresql/11/main", "-c", "config_file=/etc/postgresql/11/main/postgresql.conf"]

