# Nginx server configuration

FROM nginx:1.17

ARG WORK_DIR

WORKDIR ${WORK_DIR}

# Copy frontend folder to container
COPY frontend ${WORK_DIR}/frontend

# Copy conf file
COPY deployment/compose/translator_nginx.conf /etc/nginx/conf.d/
